apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cilium-etcd-operator
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: cilium-etcd-operator
        io.cilium/app: etcd-operator
    spec:
      serviceAccountName: cilium-etcd-operator
      hostNetwork: true
      containers:
      - name: cilium-etcd-operator
        image: docker.io/cilium/cilium-etcd-operator:v2.0.0
        imagePullPolicy: IfNotPresent
        command: [ "/usr/bin/cilium-etcd-operator" ]
        env:
        - name: "CILIUM_ETCD_OPERATOR_CLUSTER_DOMAIN"
          value: "cluster.local"
        - name: "CILIUM_ETCD_OPERATOR_ETCD_CLUSTER_SIZE"
          value: "3"
        - name: "CILIUM_ETCD_OPERATOR_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: cilium-etcd-operator
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: cilium-etcd-operator
  namespace: kube-system
rules:
- apiGroups:
  - etcd.database.coreos.com
  resources:
  - etcdclusters
  - etcdbackups
  - etcdrestores
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - deployments
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - componentstatuses
  verbs:
  - "get"
- apiGroups: ["extensions"]
  resources: ["deployments"]
  verbs: ["create", "get","list","patch","update"]
- apiGroups:
  - ""
  resources:
  - secrets
  verbs: ["get", "create", "delete","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: cilium-etcd-operator
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cilium-etcd-operator
subjects:
- kind: ServiceAccount
  name: cilium-etcd-operator
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cilium-etcd-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: etcd-operator
  namespace: kube-system
rules:
- apiGroups:
  - etcd.database.coreos.com
  resources:
  - etcdclusters
  - etcdbackups
  - etcdrestores
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - deployments
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - "*"
- apiGroups: ["extensions"]
  resources: ["deployments"]
  verbs: ["create", "get","list","patch","update"]
# The following permissions can be removed if not using S3 backup and TLS
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: etcd-operator
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: etcd-operator
subjects:
- kind: ServiceAccount
  name: cilium-etcd-sa
  namespace: kube-system
---
